### ISSUE TITLE
Not able to see wlan 0 and 1 after adding BASH ID 

### ISSUE THREAD

**Issue by Sivanesh1992** [LABORA-INF-UFG/paper-MCAK-2021#3]
hi team,

I am trying to test n3iwf by using wiki document.
my setup :
Lenova Laptop intel i5 with 12 core.(ubuntu22.04.3 OS version)
below stops i done 
![image](https://github.com/LABORA-INF-UFG/paper-MACAK-2022/assets/96040330/8b695e94-d6ed-45ac-8659-14d06ce991ed)

![image](https://github.com/LABORA-INF-UFG/paper-MACAK-2022/assets/96040330/92075e60-086b-4f49-864a-cc86ac91af3f)

![image](https://github.com/LABORA-INF-UFG/paper-MACAK-2022/assets/96040330/bd5e0983-30a1-4174-bbd5-94288cebb46f)

![image](https://github.com/LABORA-INF-UFG/paper-MACAK-2022/assets/96040330/a6d9208c-a724-477f-a2fb-894cac99d34d)

After adding BASHPID id i am not able to see WLAN0 and WLAN 1

![image](https://github.com/LABORA-INF-UFG/paper-MACAK-2022/assets/96040330/9e95af0a-a15a-42b5-96d3-2694218c1f58)

please help me to resolve the issue

**Comment by mariotlemes** [comment]
Hello,

1) It is important to use the [recommend environment ](https://github.com/LABORA-INF-UFG/paper-MACAK-2022/wiki/General-information).

2) wlan0 and wlan1, after adding bash pid, **only** will visible in namespace. Therefore, fist you need to enter in namespace or exec the command in namespace.

Regards, 
Mario

**Comment by Sivanesh1992** [comment]
HI Mario,

Thankyou for response .

1. I am using below environment 

Minimum Hardware:
CPU: Intel i5 processor.
OS: Ubuntu 22.04.3 LTS
RAM: 16GB.
Hard drive: 526GB.
NIC: 10Gbps [nl80211](https://wireless.wiki.kernel.org/en/developers/Documentation/nl80211) compatible wireless device, which supports the AP operating mode.

2.i execute below command to create a name space.

sudo ip netns add APns
sudo ip netns add UEns
sudo ip netns add UPFns

then i added a bash pid.


please correct me if i missed anything

kindly find my pc configuration.

![image](https://github.com/LABORA-INF-UFG/paper-MACAK-2022/assets/96040330/c3cff4e2-d55a-4f12-9958-d8de7b6126e9)

**Comment by Sivanesh1992** [comment]
hi mario,

I am following below document 

https://github.com/LABORA-INF-UFG/paper-MACAK-2022/wiki/Setting-up-experimental-environment

I run all command given by the document but i am getting below attached error while executing below command 

sivanesh@sivanesh:my5G-core$ sudo ip netns exec UEns dhclient wlan1
Failed to set LLMNR configuration: Link 7 not known
Failed to set MulticastDNS configuration: Link 7 not known
Failed to set domain configuration: Link 7 not known
Failed to set DNS configuration: Link 7 not known

i need to fix this issue or shall i skip this step

![image](https://github.com/LABORA-INF-UFG/paper-MACAK-2022/assets/96040330/a84c0524-f15f-4e17-8f9d-ef4bce7611bc)
